services:
  rdesktop:
    build: ./
    container_name: ros-humble
    hostname: ros-humble
    security_opt:
      - seccomp:unconfined #optional
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - RMW_IMPLEMENTATION=rmw_fastrtps_cpp
      - ROS_SUPER_CLIENT=True
      - ROS_DOMAIN_ID=0
      #- ROS_DISCOVERY_SERVER="127.0.0.1:11811;"
    volumes: 
      - ./config.yaml:/code/config.yaml
      - /dev/bus/usb:/dev/bus/usb
    device_cgroup_rules:
      - 'c 189:* rmw'
    ports:
      - 3390:3389
    shm_size: "2gb" #optional
    restart: unless-stopped
    devices:
      - /dev/ttyUSB0
      - /dev/RPLIDAR
